FROM alpine:3.6

RUN apk add --update autoconf automake build-base zlib-dev git

WORKDIR /usr/src/apps

RUN git clone https://gitlab.com/osm-c-tools/osmctools

WORKDIR /usr/src/apps/osmctools

RUN autoreconf -i && \
    ./configure && \
    make install

CMD ["echo", "done"]